name = input("Enter your name: ")
home = input("Enter home: ")
species = input("Species: ")
inumber = input("Enter id: ")
rank = input("rank: ")

print("========================================")
print("    GALACTIC FEDERATION ID CARD")
print("========================================")
print(f"Full name:   [{name}]")
print(f"Home planet: [{home}]")
print(f"Species:     [{species}]")
print(f"Rank:        [{rank}]")
print("----------------------------------------")
print(f"ID code: GF - [{inumber}]-[{home}]")
print("========================================")